### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by w3d0z** [skyworld123/module-face_recognition#1]
ERROR: Model "model-r100-ii" not found. Abort.
        Note: Please put model model-r100-ii under "model/" before running this programme.

actually, you dont upload sample model inside /model/ directory
this code isnt work without it

**Comment by skyworld123** [comment]
> ERROR: Model "model-r100-ii" not found. Abort.
> Note: Please put model model-r100-ii under "model/" before running this programme.
> 
> actually, you dont upload sample model inside /model/ directory
> this code isnt work without it

I'm sorry about this but the original model "model-r100-ii" from [InsightFace](https://github.com/deepinsight/insightface) is too large (around 249MB), and it will cause some trouble if I directly upload it to GitHub.
To solve this problem, you can download "model-r100-ii" from [model_zoo](https://github.com/deepinsight/insightface/tree/master/model_zoo). "model-r100-ii" is the first face recognition model with backbone "R100 (mxnet)". Extract directory “model-r100-ii” from "model-r100-ii.zip" and put it under my model/ directory.
By the way, remember to rename the inner files (model-0000.params -> -0000.params, model-symbol.json -> -symbol.json) to avoid some bugs in the code.
If you're interested, you can also download the second face recognition model in model_zoo (MFN(mxnet)) and try it in the same way. This model takes much less space but presents lower recognition accuracy than "model-r100-ii".
